### ISSUE TITLE
Can't see global tags archive page.

### ISSUE THREAD

**Issue by schuhwerk** [dol-lab/spaces-global-tags#35]
I created a tag (both in gutenberg and a frontend-editor).
The link shows properly.
![image](https://user-images.githubusercontent.com/865652/80980983-9c947600-8e29-11ea-80d7-c57770aa9ad7.png)

When I click the link I get an empty page.
`Failed to load resource: the server responded with a status of 404 (Not Found)`

There is no output to the error-log. Am I doing something wrong?
![image](https://user-images.githubusercontent.com/865652/80981420-3c520400-8e2a-11ea-853d-a78d161e2826.png)

**Comment by neverything** [comment]
Ahh maybe the routine to flush the permalinks didn't run yet. Could you try to manually update the permalinks for the home space?

**Comment by schuhwerk** [comment]
Flushing the permalinks (in the home theme) helped. (I set them to plain and back.)
![image](https://user-images.githubusercontent.com/865652/82758221-7ab56000-9de5-11ea-8eea-6080c52a5056.png)
Maybe do it on plugin initialization? How does the plugin decide which blog to use for the overview page?

**Comment by neverything** [comment]
> Maybe do it on plugin initialization?
This is sort of done, but might not be working stable, see https://github.com/dol-lab/spaces-global-tags/blob/master/spaces-global-tags.php#L233-L247

> How does the plugin decide which blog to use for the overview page?
It does it by running the following, maybe not the nicest solution: https://github.com/dol-lab/spaces-global-tags/blob/master/spaces-global-tags.php#L426-L454

**Comment by neverything** [comment]
Closing for now
